version: "3"

services:
  client:
    build: ./client
    ports:
      - 8080:8080
    volumes:
      - ./client:/app
  server:
    build: ./server
    links:
      - mongodb
    depends_on:
      - mongodb
    command: ["./wait-for-it.sh", "mongodb:27017", "--", "yarn", "dev"]
    ports:
      - 8081:8081
    volumes:
      - ./server:/app
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./usr/local/var/mongodb:/data/db
    ports:
      - 27017:27017
    command: ["mongod", "--logpath", "/dev/null"]
